added python 3.6 specific stuff
bclary/mozilla-bitbar-docker pull request #11
Opened 2019-08-13 17:56 UTC by tarekziade

This patche would allow me to run the conditioned profile task on android devices. see https://bugzilla.mozilla.org/show_bug.cgi?id=1562870

I am using a modern Python version along with a couple of python packages, on requires 3.6

I don't think this change will affect the current docker image in any particular way, besides the fact that it will have 3.6 installed.

2019-08-13 21:14 UTC, bclary requested changes
A few comments...

* We already have curl.
* You should add the repository above where we add the openjdk.
* Try not to create so many intermediate images with the separate RUN commands. You should be able to include some of these installs in the existing RUN... apt-get install
* We need to also version this change and test it.
* I'm not sure about the best approaching for getting python 3.6 in these images. @aerickson can talk with bitbar to see what they say.

@aerickson should have the final say here.

2019-08-13 21:17 UTC, bclary commented
PS. The curl and pip commands should go in the final RUN command as well.

2019-08-13 21:42 UTC, aerickson reviewed
From reading the bug it seems like you want to run on an emulated devices. This Dockerfile is only used by android hardware devices.

2019-08-13 21:42 UTC, aerickson commented on Dockerfile
> +# adding a couple of packages for the conditioned profiles
I think the test framework should install pips.

Changing this image is a very heavyweight process. We don't want to start installing testing deps here.

2019-08-13 21:42 UTC, aerickson commented on Dockerfile
> +RUN add-apt-repository ppa:jonathonf/python-3.6
Python 3 and pip for it is available in the official/default repos, there's no need for a PPA for them.

```
python3
python3-pip
```

2019-08-14 06:35 UTC, tarekziade commented on Dockerfile
> +# adding a couple of packages for the conditioned profiles
We can't vendor python 3 only packages at this point (that should be possible in the future but not now) 
I understand that changing this Dockerfile is a very heavyweight process, but why adding two more package changes anything ? the Dockerfile installs mozdevice for instance.

2019-08-14 06:36 UTC, tarekziade commented on Dockerfile
> +RUN add-apt-repository ppa:jonathonf/python-3.6
This version of Ubuntu comes with Python 3.5, this installs Python 3.6

2019-08-14 06:41 UTC, tarekziade commented
@aerickson using the emulator was the first intent because I did not want the extra complexity to run things on bitbar. But I reached a blocker using emulators, as we want to run the script on arm as well as x86. android *arm* emulators are unusable from a x86 device (like 100x slower) and often crash. 

I understand from your feedback that changing this Dockerfile is a pain, but I don't have any other way. Is there anything I can do to help getting this done ? Happy to go through that heavy weight process or at least help.

2019-08-14 21:00 UTC, tarekziade reviewed
@bclary reviews done

2019-08-20 09:37 UTC, tarekziade commented
supersed by https://github.com/bclary/mozilla-bitbar-docker/pull/12

2019-08-20 09:37 UTC, closed without merging