Stackdriver logging
bclary/mozilla-bitbar-docker pull request #7
Opened 2019-05-03 01:09 UTC by aerickson

2019-05-08 13:49 UTC, bclary requested changes
Do we have a try run ?

Over all looks great. I'd like to talk about the shell=True on Popen and the stackdriver credentials. Ping me later.

2019-05-08 13:49 UTC, bclary commented on scripts/run_gw.py
> +                        shell=True)
Are you using shell=True because you are passing a string as the args? I don't like shell=True unless we absolutely positively absolutely have to use it.

We can just use a cmd_arr list for args instead and elminate shell=True can't we?

2019-05-08 13:49 UTC, bclary commented on scripts/run_gw.py
> +proc = subprocess.Popen(cmd_str,
cmd_arr

2019-05-08 13:49 UTC, bclary commented on build.sh
> +
Let's talk about this. Ping me on irc.

2019-05-08 17:40 UTC, aerickson commented on scripts/run_gw.py
> +                        shell=True)
I was struggling with getting g-w running and I thought it shell fixed it, but it was an option. 

Switched back to use the array.

2019-05-08 17:41 UTC, aerickson commented
> Do we have a try run ?

Try run added to the description up top.

2019-05-28 17:53 UTC, bclary approved these changes
Looks ok to me. I'd like to see a test run before we deploy everywhere. Perhaps we can do that with the new platform tools image.

2019-05-28 19:47 UTC, merged